### ISSUE TITLE
Error in 'prepare_transcripts'

### ISSUE THREAD

**Issue by Sunpeisen** [xryanglab/RiboCode#14]
Hi,

When I try to run prepare_transcripts with command line:

`prepare_transcripts -g Arabidopsis_thaliana.TAIR10.41.gtf -f tair10.fa -o tair10_annot/`

I got this error:

> Preparing annotation files ...
> 	Reading the GTF file: Arabidopsis_thaliana.TAIR10.41.gtf .......
> Traceback (most recent call last):
>   File "/usr/local/bin/prepare_transcripts", line 11, in <module>
>     load_entry_point('RiboCode==1.2.10', 'console_scripts', 'prepare_transcripts')()
>   File "/usr/local/lib/python3.6/dist-packages/RiboCode/prepare_transcripts.py", line 388, in main
>     processTranscripts(args.genomeFasta,args.gtfFile,args.out_dir)
>   File "/usr/local/lib/python3.6/dist-packages/RiboCode/prepare_transcripts.py", line 308, in processTranscripts
>     gene_dict,transcript_dict = readGTF(gtfFile)
>   File "/usr/local/lib/python3.6/dist-packages/RiboCode/prepare_transcripts.py", line 174, in readGTF
>     field_dict = parsing_line(line)
>   File "/usr/local/lib/python3.6/dist-packages/RiboCode/prepare_transcripts.py", line 102, in parsing_line
>     field_dict = {"chrom": intern(chrom),"source":source,"feature": intern(feature),"iv":iv,"attr":parsing_attr(attr)}
>   File "/usr/local/lib/python3.6/dist-packages/RiboCode/prepare_transcripts.py", line 74, in parsing_attr
>     k,v = i.strip().split(" ",1)
> ValueError: not enough values to unpack (expected 2, got 1)

The gtf file was downloaded from http://plants.ensembl.org/index.html
Could you show me some advice about this error?
Have a nice day.

**Comment by xzt41** [comment]
This error is due to unexpected semicolon in the attribute string (e.g., gene_id "AT1G14040"; gene_name **"PHO1;H3"**; gene_source "araport11"; gene_biotype "protein_coding";).  It has been fixed in the update package.
