### ISSUE TITLE
Error in 'RiboCode'

### ISSUE THREAD

**Issue by PSSUN** [xryanglab/RiboCode#15]
Hi, 

When I try to run RiboCode:

`RiboCode -a annot/ -c config.txt -l no -g -o result/`

I got this error:

> 	Loading transcripts.pickle ...
> 	Reading bam file: newstarAligned.toTranscriptome.out.bam......
> Finished reading bam file!
> 100% has finished! 
> 	Writing the results to file .....
> Traceback (most recent call last):
>   File "/usr/local/bin/RiboCode", line 11, in <module>
>     load_entry_point('RiboCode==1.2.10', 'console_scripts', 'RiboCode')()
>   File "/usr/local/lib/python3.6/dist-packages/RiboCode/RiboCode.py", line 63, in main
>     output_gtf=output_gtf, output_bed=output_bed)
>   File "/usr/local/lib/python3.6/dist-packages/RiboCode/detectORF.py", line 379, in main
>     write_result(orf_results,outname)
>   File "/usr/local/lib/python3.6/dist-packages/RiboCode/detectORF.py", line 156, in write_result
>     header = "\t".join(list(orf_results[0].keys())[:-1])
> IndexError: list index out of range

I really don't know how to deal with this problem.Could you show me some advice?

**Comment by xzt41** [comment]
The is an error since there was no translated ORF detected (in the update package, it would give a warning). You can try to use a higher p-value cutoff.

**Comment by Sunpeisen** [comment]
Hi,

When I try to run RiboCode again, here comes another error:

> Loading transcripts.pickle ...
> Loading Psites from newgenomeAligned.toTranscriptome.out......
> _psites.hd5/home/sun/sps/01_software/venv/lib/python3.6/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
>   "Use dataset[()] instead.", H5pyDeprecationWarning)
> Opps, no translated ORFs were detected.
> 
> Writing the results to file .....
> Traceback (most recent call last):
>   File "/home/sun/sps/01_software/venv/bin/RiboCode", line 11, in <module>
>     sys.exit(main())
>   File "/home/sun/sps/01_software/venv/lib/python3.6/site-packages/RiboCode/RiboCode.py", line 63, in main
>     output_gtf=output_gtf, output_bed=output_bed)
>   File "/home/sun/sps/01_software/venv/lib/python3.6/site-packages/RiboCode/detectORF.py", line 382, in main
>     write_result(orf_results,outname)
>   File "/home/sun/sps/01_software/venv/lib/python3.6/site-packages/RiboCode/detectORF.py", line 156, in write_result
>     header = "\t".join(list(orf_results[0].keys())[:-1])
> IndexError: list index out of range

It seems here's something wrong with package H5py when loading Psites from newgenomeAligned.toTranscriptome.out

**Comment by zhengtaoxiao** [comment]
Hi, this error message is triggered because no ORFs were identified.  The deprecation warning message from H5py was just a reminder for the developers.  We will avoid these superfluous messages in the next version.

**Comment by PSSUN** [comment]
Thank you for your reply.
