### ISSUE TITLE
prepare_transcripts not taking multiple CDSs into account

### ISSUE THREAD

**Issue by Eduardo-vsouza** [xryanglab/RiboCode#33]
Hi,

I'm trying to run prepare_transcripts to extract transcripts and CDSs from a GTF file. The problem is that this GTF file contains transcripts with multiple CDSs and, when checking the output file 'transcripts_cds.txt' from prepare_transcripts, it seems to contain only one CDS for each transcript. Does RiboCode support transcripts with multiple CDSs at all? Any way around this?

**Comment by zhengtaoxiao** [comment]
The purpose of RiboCode is to search the novel ORFs. RiboCode chose one represent CDS for inferring the p-site information. The overlapped CDSs will only be counted once. It then predicts the ORFs based on inferred p-site information.
