### ISSUE TITLE
No obviously periodicity are detected from bam file, it could be due to poor quality sequencing. Please check the metagene plots and try again by lowering the value of frame0_percent

### ISSUE THREAD

**Issue by z626093820** [xryanglab/RiboCode#39]
I am using the QC data to do my best analysis and I am not getting the following error, how can I change the p-value or how can I fix this problem？
error:No obviously periodicity are detected from bam file, it could be due to poor quality sequencing. Please check the metagene plots and try again by lowering the value of frame0_percent

thank you!

**Comment by s0kan** [comment]
I'm having the same issue. Could you please share how you solved it? Thank you in advance
