### ISSUE TITLE
Error, the references in bam are different from transcriptome annotation

### ISSUE THREAD

**Issue by KONeill872** [xryanglab/RiboCode#56]
Hi, 

I got the following error when running my script:

`Error, the references in bam are different from transcriptome annotation`

It seems to throw this as my reads were aligned to the transcriptome and have the transcript version ID instead of just the transcript ID. Is it possible for the output of the prepare_transcript function to include the version number? 

Thanks

**Comment by xvce** [comment]
I'm encountering the same issue. Could you please share how you resolved it? Thank you.
