### ISSUE TITLE
请问如何进行lncRNA的ORF鉴定

### ISSUE THREAD

**Issue by DooYal** [xryanglab/RiboCode#60]
prepare_transcripts这一步用gencode.lncRNA.gtf生成的文件中，cds文件就已经是空的了，后续用metaplots直接报错no orf出不了结果了
![屏幕截图 2024-02-07 152137](https://github.com/xryanglab/RiboCode/assets/31724229/896f3dc2-4b4f-4601-af3c-cb7b04036acc)
上面是lncRNA的gtf生成的，下面是完整gtf生成的

**Comment by netwchao** [comment]
> prepare_transcripts这一步用gencode.lncRNA.gtf生成的文件中，cds文件就已经是空的了，后续用metaplots直接报错no orf出不了结果了 ![屏幕截图 2024-02-07 152137](https://private-user-images.githubusercontent.com/31724229/302893221-896f3dc2-4b4f-4601-af3c-cb7b04036acc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzIyMzIsIm5iZiI6MTcyMTAzMTkzMiwicGF0aCI6Ii8zMTcyNDIyOS8zMDI4OTMyMjEtODk2ZjNkYzItNGI0Zi00NjAxLWFmM2MtY2I3YjA0MDM2YWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA4MjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YjU1MTY3NDQxZjkwZTE0MzExMmIzOWY2YjcwZTEwMmYyYTliNzliNmVkOGJiM2ZjNzgzODU1Y2ZhOTZiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O2wU7IGpTElyljDq9YN0dLFr331q8cLFSEAAmsf77vo) 上面是lncRNA的gtf生成的，下面是完整gtf生成的

您好，请问您解决了吗？我遇到了同样的问题。

**Comment by DooYal** [comment]
> > prepare_transcripts这一步用gencode.lncRNA.gtf生成的文件中，cds文件就已经是空的了，后续用metaplots直接报错no orf出不了结果了 ![屏幕截图 2024-02-07 152137](https://private-user-images.githubusercontent.com/31724229/302893221-896f3dc2-4b4f-4601-af3c-cb7b04036acc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzIyMzIsIm5iZiI6MTcyMTAzMTkzMiwicGF0aCI6Ii8zMTcyNDIyOS8zMDI4OTMyMjEtODk2ZjNkYzItNGI0Zi00NjAxLWFmM2MtY2I3YjA0MDM2YWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA4MjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YjU1MTY3NDQxZjkwZTE0MzExMmIzOWY2YjcwZTEwMmYyYTliNzliNmVkOGJiM2ZjNzgzODU1Y2ZhOTZiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O2wU7IGpTElyljDq9YN0dLFr331q8cLFSEAAmsf77vo) 上面是lncRNA的gtf生成的，下面是完整gtf生成的
> 
> 您好，请问您解决了吗？我遇到了同样的问题。

得用全转录本，lncRNA没有CDS注释的
